trigger:
  branches:
    include:
      - '*'
  paths:
    include:
      - 'PRN.Src/*'

parameters:
- name: runTests
  displayName: Run tests
  type: boolean
  default: true
- name: sonarqubeInstance
  displayName: 'Select SonarQube for v9.9 or SonarQubeLatest for 10.4'
  type: string
  default: 'SonarQube'
  values:
  - 'SonarQube'
  - 'SonarQubeLatest'

pool: DEFRA-COMMON-ubuntu2004-SSV3

variables:
  - template: vars/Team-4_QA-development.yaml
  - name: solutionFolder
    value: PRN.Src
  - name: projectFolder
    value: EPR.Antivirus.Function
  - name: testProjectFolder
    value: 'EPR.Antivirus.Function.UnitTests'
  - name: sonarQubeProjectKey
    value: epr-anti-virus-function-app
  - name: sonarQubeProjectName
    value: epr-anti-virus-function-app
  - name: runNugetTasks
    value: true

resources:
  repositories:
    - repository: CommonTemplates
      name: defra/epr-prn-accreditation-back-end
      type: github
      endpoint: defra
      ref: main

extends:
  template: epr-build-pipeline.yaml@CommonTemplates
  parameters:
    solutionFolder: ${{ variables.solutionFolder }}
    projectFolder: ${{ variables.projectFolder }}
    testProjectFolder: ${{ variables.testProjectFolder }}
    sonarQubeProjectKey: ${{ variables.sonarQubeProjectKey }}
    sonarQubeProjectName: ${{ variables.sonarQubeProjectName }}
    runTests: ${{ parameters.runTests }}
    azureSubscription: $(azureSubscription)
    acrAzureContainerRegistryName: $(acr.azureContainerRegistryName)
    acrRepositoryName: $(acr.repositoryName)
    branchName: ${{ replace(replace(variables['Build.SourceBranch'], 'refs/heads/', ''), '/', '_') }}
    runNugetTasks: ${{ variables.runNugetTasks }}
    serviceName: $(serviceName)
    sonarqubeInstance: ${{ parameters.sonarqubeInstance }}
