variables:
  azureSubscription: 'AZR-RWD-PRD1'
  docker.imageName: 'accreditationbackend'
  acr.azureContainerRegistryName: 'prdrwdinfac1401'
  acr.repositoryName: 'eprprnaccreditationbackend'
  serviceName: 'prdrwdwebfa1405'
