variables:
  azureSubscription: 'AZR-RWD-PRD1'
  docker.imageName: 'antivirusresult'
  acr.azureContainerRegistryName: 'prdrwdinfac1401'
  acr.repositoryName: 'antivirusrepository'
  serviceName: 'prdrwdwebfa1405'
